#importar imagen base de python
FROM python:3.12-slim 

#Crear en el contenedor Carpeta Trabajo

WORKDIR /app

#Copiar los requisitos al contenedor
COPY requirements.txt . 

#Instamos las dependencias de FastAPI 
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el codigo del servidor
COPY ./app ./app

#Exponer el puerto de trabajo
EXPOSE 5000

#Comando a ejecutar levantar el Sevidor
CMD ["uvicorn", "app.main:app", "--host","0.0.0.0", "--port", "5000", "--reload"]



